spring:
  # Database 설정
  datasource:
    driver-class-name:
    url:            # DB 연결 주소
    username:        # DB 접속 ID
    password:         # DB 접속 PW

  # JPA 설정
  jpa:
    database-platform:
    hibernate:
      ddl-auto: none        # DB 초기화 전략 (none, create, create-drop, update, validate)
    properties:
      hibernate:
        dialect:
        format_sql: true      # 쿼리 로그 포맷 (정렬)
        show_sql: true        # 쿼리 로그 출력

  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB